### ISSUE TITLE
What is the meaning of C in formulation 9

### ISSUE THREAD

**Issue by B10532021** [longcw/crossview_3d_pose_tracking#10]
Hi thanks for your great work
But there is something I cant understand?
What is the meaning C in formulation 9?
And the formulation 11 , why can the l2 norm can eliminate the bias between 2D different view?
Looking forward to your reply

Best Regards

**Comment by longcw** [comment]
Hi thank you for your interests, the C matrix is used for solving the triangulation problem. It's recommended to read more from Multiple view geometry in computer vision. Cambridge university press, 2003 or https://stackoverflow.com/questions/2276445/triangulation-direct-linear-transform

But anyway you can also use that from opencv directly https://docs.opencv.org/3.4/d0/dbd/group__triangulation.html

**Comment by B10532021** [comment]
Hi @longcw 
Thanks for your reply!
I've already figured this out. But still, thanks a lot!
