### ISSUE TITLE
Excellent work. Inquiry about if 3D pose data sets are required for training

### ISSUE THREAD

**Issue by happyCodingSusan** [longcw/crossview_3d_pose_tracking#2]
@longcw , 
Very impressive work and results! Thank you!

If you do not mind, I want to ask you a question. For methods of 3D pose estimation from a single depth image, a large amount of 3D pose datasets with ground truth labels are required for training, and the trained model will only work for the camera used to capture the datasets. I wonder for your method, if only 2D pose datasets with ground truth labels are required. If so, your method has an obvious advantage because there are lots of public 2D pose datasets can be used for 2D human body pose training. Moreover, collecting and labeling 2D pose is much easier than collecting and labeling 3D pose.

Thank you very much for your kind reply.

**Comment by longcw** [comment]
Hey @happyCodingSusan, you are right the input is 2D pose estimation and you can use any 2D pose dataset as well as models to generate the 2D poses. The 3D pose labels are not required if you don't need evaluation in 3-space. The only requirement for this 3D pose estimation method is the multiple calibrated cameras.
